# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea45b3400cb0f309fd4194f2ce0ce7e4a9db9ed0cef35801e53bd36d2716876d1e5672ed0fd82bbfa79400773c6daba3bf875369ebbdff5e86609feb3a0e0a9

test:
  secret_key_base: d4b6733d293e721dfac93be580e8d14ffb44a6e76e63139b323ff830e73edba34b2237abfacf71b40d27b1f451d43907e40d4bfc8d2aec9b346ff6892a0fb19c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
